[[pages]]
name = "Naviation"
icon = "🇲🇲"
is_section = true

[[pages]]
path = ".streamlit/aboutus.toml"
name = "About Us!"
icon = "🫂"

[[pages]]
path = "test2.py"
name = "**Intermediate Level Grammar & Spelling Checker**"
icon = "🔍"

[[pages]]
path = ".streamlit/reference.py"
name = "Our Appreciation!"
icon = "📍"